services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  milvus:
    image: milvusdb/milvus:v2.4.5
    environment:
      ETCD_USE_EMBED: "true"
      MINIO_USE_EMBED: "true"
      COMMON_STORAGETYPE: local
    ports: ["19530:19530"]
    volumes: [ "milvus-data:/var/lib/milvus" ]
  attu:
    image: zilliz/attu:latest
    environment:
      MILVUS_URL: "http://milvus:19530"
    ports: ["8000:3000"]
    depends_on: [milvus]
volumes:
  pgdata:
  milvus-data:
